{% set name = "gEconpy" %}
{% set version = "2.0.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geconpy-{{ version }}.tar.gz
  sha256: f1b512637b9a70f8f161ba8ba0d4ea01a42473b0166d8035f4bb9e455d8c66ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - versioneer
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numba
    - numpy
    - pandas
    - pymc
    - pymc-extras
    - preliz
    - pyparsing
    - pytensor
    - scipy
    - setuptools
    - sympy <1.13
    - sympytensor
    - ipython
    - xarray

test:
  imports:
    - gEconpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jessegrabowski/gEconpy
  summary: A package for solving, estimating, and analyzing DSGE models
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jessegrabowski
